image: node:alpine

before_script:
  - npm install

cache:
  paths:
    - node_modules/

publish:
  stage: deploy
  only:
    - master
    - tags
  except:
    - triggers
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN\n@idearium:registry=https://registry.npmjs.org/" > .npmrc
    - npm publish
