'use strict';

module.exports = {
    'env': {
        'es6': true,
        'mongo': true,
        'node': true,
    },
    'extends': '@idearium/eslint-config/src/common',
    'parserOptions': {
        'ecmaVersion': 6,
        'sourceType': 'script',
    },
    'rules': {
        'handle-callback-err': ['error', '^(e|err|error)$'],
        'no-path-concat': 'error',
        'no-process-env': 'error',
        'no-process-exit': 'error',
        'no-restricted-modules': 'off',
        'no-sync': 'error',

        'arrow-body-style': 'error',
        'arrow-parens': ['error', 'as-needed', { requireForBlockBody: true }],
        'arrow-spacing': 'error',
        'constructor-super': 'error',
        'generator-star-spacing': 'error',
        'no-class-assign': 'error',
        'no-confusing-arrow': ['error', { allowParens: true }],
        'no-const-assign': 'error',
        'no-dupe-class-members': 'error',
        'no-duplicate-imports': ['error', { includeExports: true }],
        'no-new-symbol': 'error',
        'no-restricted-imports': 'off',
        'no-this-before-super': 'error',
        'no-useless-computed-key': 'error',
        'no-useless-constructor': 'error',
        'no-useless-rename': 'error',
        'no-var': 'error',
        'object-shorthand': 'error',
        'prefer-arrow-callback': 'error',
        'prefer-const': 'error',
        'prefer-destructuring': 'error',
        'prefer-numeric-literals': 'off',
        'prefer-rest-params': 'error',
        'prefer-spread': 'error',
        'prefer-template': 'error',
        'require-yield': 'error',
        'rest-spread-spacing': 'error',
        'sort-imports': 'error',
        'symbol-description': 'error',
        'template-curly-spacing': 'error',
        'yield-star-spacing': 'error',
    }
};
