name: Publish @idearium/eslint-config

on:
    push:
        tags:
            - 'v*'

permissions:
    contents: read

jobs:
    ci:
        name: CI
        uses: ./.github/workflows/ci.yaml
        secrets: inherit

    environment:
        name: Setup environment
        uses: idearium/actions/.github/workflows/environment.yaml@v4

    publish:
        name: Publish
        needs: [ci, environment]
        runs-on: ubuntu-latest
        timeout-minutes: 15
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v6
              with:
                  persist-credentials: false

            - uses: actions/setup-node@v6
              with:
                  node-version: '24'
                  package-manager-cache: false
                  registry-url: https://registry.npmjs.org

            - run: npm ci

            - name: Publish (beta)
              if: needs.environment.outputs.CI_ENV == 'beta'
              run: npm publish --tag beta --access public
              working-directory: packages/eslint-config

            - name: Publish (production)
              if: needs.environment.outputs.CI_ENV == 'production'
              run: npm publish --access public
              working-directory: packages/eslint-config
